### ISSUE TITLE
Checklist for the final review

### ISSUE THREAD

**Issue by flor14** [UBC-MDS/ds-toolbox#59]
@joelostblom here are some comments that can be useful for the final review on the base of the experience with my chapters. 

**Formatting issues**

- [x] All the points in #11 
- [x]  Number of `#` in the titles of the slides.
- [x]  Same phrases to finish and start slides.
- [x]  The code is properly formatted in the `moduleX.md` files.
- [x]  The code is properly formatted in assignments and quizzes (including options).
- [x]  The colors/format of the questions are similar for all the assignments and quizzes.
- [x] The slides do have not much text or content
- [x] The images are well proportioned and centered when they should be.

**Grammar and spelling - Readability**

- [x] Typos, problems with sentence structure, etc
- [x] Could the text be improved including more/fewer details for the students?

**Tutorial structure**

- [x] The learning outcomes are clear and in relation to what is explained.
- [x] All the exercises have sense in the order they were placed in the modules.
- [x] All the assignments and quizzes are aligned with the learning outcomes as they have been defined.
- [x] The names of the slides/videos and exercises are appropriate and clear in `moduleX.md` files.
- [x] All the exercises (in the modules, assignments, and quizzes) provide feedback for the students when there is an incorrect option as a potential answer.
- [x] All the questions provide as correct the correct answer.
- [x] The quizzes and assignments questions are assigned points fairly in relation to how complex they are to solve.
- [x] The quizzes and assignments settings are working as expected (for example, the answers are shuffled and the number of attempts the students have is the appropriate ones)
- [x] Settings quizzes
- [x] If we are using emojis/ colors to highlight a particular part/section of the tutorial this clue is maintained during all the modules.
- [x] Emojis for questions? "Funny names"?
- [x] What did we learn" -> "What did we learn?" or "What we learned"

**Content**

- [x] All the content is technically correct and up to date
- [x] Add how to use the keyboard in chapter2 (if there is not there yet)
